version: "3"
services:
  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --requirepass redis123456
    networks:
      mynet:
        ipv4_address: 172.31.0.101
    ports:
      - "6379:6379"
  db:
    image: mysql:latest
    container_name: database
    networks:
      mynet:
        ipv4_address: 172.31.0.100
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: db123
  consul:
    command: -server -bootstrap -rejoin
    image: progrium/consul:latest
    hostname: "registry"
    networks:
      - mynet
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
  api:
    command: --registry_address=registry:8500 --register_interval=5 --register_ttl=10 api --handler=web --namespace=com.fxms.web
    image: microhq/micro
    container_name: api
    networks:
      - mynet
    ports:
      - "8080:8080"
    environment:
      - MICRO_API_HANDLER=web
      - MICRO_NAMESPACE=com.fxms.web
  proxy:
    command: --registry_address=registry:8500 --register_interval=5 --register_ttl=10 proxy
    image: microhq/micro
    container_name: proxy
    networks:
      - mynet
    links:
      - consul
    ports:
      - "8081:8081"
  web:
    command: --registry_address=registry:8500 --register_interval=5 --register_ttl=10 web
    image: microhq/micro
    networks:
      - mynet
    links:
      - consul
    ports:
      - "8082:8082"

################################   auth_srv   ##############################
  auth_srv:
    command: --registry_address=registry:8500 --register_interval=5 --register_ttl=10
    build: ./srv/auth
    container_name: auth_srv
    networks:
      - mynet
    depends_on:
      - db
################################   user_srv   ##############################
#  user_srv:
#    command: --registry_address=registry:8500 --register_interval=5 --register_ttl=10
#    build: ./srv/user
#    container_name: user_srv
#    networks:
#      - mynet
#    depends_on:
#      - db
################################   auth_web   ##############################
#  auth_web:
#    command: --registry_address=registry:8500 --register_interval=5 --register_ttl=10
#    build: ./web/auth
#    networks:
#      - mynet
################################  center_web  ##############################
  center_web:
    command: --registry_address=registry:8500 --register_interval=5 --register_ttl=10
    build: ./web/center
    networks:
      - mynet
################################   user_web   ##############################
  user_web:
    command: --registry_address=registry:8500 --register_interval=5 --register_ttl=10
    build: ./web/user
    networks:
      - mynet

#**************************************************************************#
#*************************** services for debug ***************************#
#**************************************************************************#


############################  auth_srv_debug  ##############################
#  auth_srv_debug:
#    command: -- --registry_address=registry:8500 --register_interval=5 --register_ttl=10
#    build:
#      context: srv/auth
#      dockerfile: Dockerfile.debug
#    privileged: true
#    networks:
#      - mynet
#    ports:
#      - "40001:40000"
############################  user_srv_debug  ##############################
  user_srv_debug:
    command: -- --registry_address=registry:8500 --register_interval=5 --register_ttl=10
    build:
      context: srv/user
      dockerfile: Dockerfile.debug
    privileged: true
    networks:
      - mynet
    ports:
      - "40002:40000"
###########################  center_web_debug  #############################
#  center_web_debug:
#    command: -- --registry_address=registry:8500 --register_interval=5 --register_ttl=10
#    build:
#      context: web/center
#      dockerfile: web/center/Dockerfile.debug
#    privileged: true
#    networks:
#      - mynet
#    ports:
#      - "50000:40000"
############################  auth_web_debug  ##############################
  auth_web_debug:
    command: -- --registry_address=registry:8500 --register_interval=5 --register_ttl=10
    build:
      context: web/auth
      dockerfile: Dockerfile.debug
    privileged: true
    networks:
      - mynet
    ports:
      - "50001:40000"
############################  user_web_debug  ##############################
#  user_web_debug:
#    command: -- --registry_address=registry:8500 --register_interval=5 --register_ttl=10
#    build:
#      context: web/user
#      dockerfile: web/user/Dockerfile.debug
#    privileged: true
#    networks:
#      - mynet
#    ports:
#      - "50002:40000"



networks:
  mynet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.0.0/16
