// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type IdResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdResponse) Reset()         { *m = IdResponse{} }
func (m *IdResponse) String() string { return proto.CompactTextString(m) }
func (*IdResponse) ProtoMessage()    {}
func (*IdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *IdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdResponse.Unmarshal(m, b)
}
func (m *IdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdResponse.Marshal(b, m, deterministic)
}
func (m *IdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdResponse.Merge(m, src)
}
func (m *IdResponse) XXX_Size() int {
	return xxx_messageInfo_IdResponse.Size(m)
}
func (m *IdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IdResponse proto.InternalMessageInfo

func (m *IdResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type UpdateInfo struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Cols                 []string `protobuf:"bytes,2,rep,name=cols,proto3" json:"cols,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateInfo) Reset()         { *m = UpdateInfo{} }
func (m *UpdateInfo) String() string { return proto.CompactTextString(m) }
func (*UpdateInfo) ProtoMessage()    {}
func (*UpdateInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *UpdateInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateInfo.Unmarshal(m, b)
}
func (m *UpdateInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateInfo.Marshal(b, m, deterministic)
}
func (m *UpdateInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateInfo.Merge(m, src)
}
func (m *UpdateInfo) XXX_Size() int {
	return xxx_messageInfo_UpdateInfo.Size(m)
}
func (m *UpdateInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateInfo proto.InternalMessageInfo

func (m *UpdateInfo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateInfo) GetCols() []string {
	if m != nil {
		return m.Cols
	}
	return nil
}

type ErrorMessage struct {
	ErrCode              string   `protobuf:"bytes,1,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
	ErrMessage           string   `protobuf:"bytes,2,opt,name=err_message,json=errMessage,proto3" json:"err_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorMessage) Reset()         { *m = ErrorMessage{} }
func (m *ErrorMessage) String() string { return proto.CompactTextString(m) }
func (*ErrorMessage) ProtoMessage()    {}
func (*ErrorMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *ErrorMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorMessage.Unmarshal(m, b)
}
func (m *ErrorMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorMessage.Marshal(b, m, deterministic)
}
func (m *ErrorMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorMessage.Merge(m, src)
}
func (m *ErrorMessage) XXX_Size() int {
	return xxx_messageInfo_ErrorMessage.Size(m)
}
func (m *ErrorMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorMessage proto.InternalMessageInfo

func (m *ErrorMessage) GetErrCode() string {
	if m != nil {
		return m.ErrCode
	}
	return ""
}

func (m *ErrorMessage) GetErrMessage() string {
	if m != nil {
		return m.ErrMessage
	}
	return ""
}

func init() {
	proto.RegisterType((*IdResponse)(nil), "mspkg.api.IdResponse")
	proto.RegisterType((*UpdateInfo)(nil), "mspkg.api.UpdateInfo")
	proto.RegisterType((*ErrorMessage)(nil), "mspkg.api.ErrorMessage")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 202 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8f, 0xb1, 0x4a, 0xc6, 0x30,
	0x14, 0x46, 0x69, 0x2a, 0x6a, 0xae, 0xe2, 0x90, 0xa9, 0x82, 0x60, 0xe9, 0x54, 0x1c, 0x1a, 0xc1,
	0x37, 0x50, 0x1c, 0x2a, 0xb8, 0x04, 0x5c, 0x5c, 0x24, 0x6d, 0x6e, 0x6a, 0xb0, 0xe9, 0x0d, 0x37,
	0x15, 0xf4, 0xed, 0xc5, 0x88, 0xcb, 0xbf, 0x7d, 0x70, 0xbe, 0x33, 0x1c, 0x90, 0x36, 0x85, 0x21,
	0x31, 0xed, 0xa4, 0x64, 0xcc, 0xe9, 0x63, 0x19, 0x6c, 0x0a, 0xdd, 0x15, 0xc0, 0xe8, 0x0c, 0xe6,
	0x44, 0x5b, 0x46, 0x75, 0x01, 0x22, 0xb8, 0xa6, 0x6a, 0xab, 0xbe, 0x36, 0x22, 0xb8, 0xee, 0x16,
	0xe0, 0x25, 0x39, 0xbb, 0xe3, 0xb8, 0x79, 0x3a, 0xa4, 0x4a, 0xc1, 0xd1, 0x4c, 0x6b, 0x6e, 0x44,
	0x5b, 0xf7, 0xd2, 0x94, 0xdd, 0x3d, 0xc1, 0xf9, 0x23, 0x33, 0xf1, 0x33, 0xe6, 0x6c, 0x17, 0x54,
	0x97, 0x70, 0x8a, 0xcc, 0x6f, 0x33, 0x39, 0x2c, 0xa6, 0x34, 0x27, 0xc8, 0xfc, 0x40, 0x0e, 0xd5,
	0x35, 0x9c, 0xfd, 0xa2, 0xf8, 0xf7, 0x6c, 0x44, 0xa1, 0x80, 0xfc, 0xef, 0xde, 0xdf, 0xbc, 0xf6,
	0x4b, 0xd8, 0xdf, 0x3f, 0xa7, 0x61, 0xa6, 0xa8, 0x7d, 0x70, 0xb8, 0xfa, 0xf5, 0x5b, 0xfb, 0xaf,
	0x98, 0x75, 0x29, 0xd0, 0x25, 0x47, 0xdb, 0x14, 0xa6, 0xe3, 0x32, 0xef, 0x7e, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x54, 0xb3, 0xd3, 0xe7, 0xe6, 0x00, 0x00, 0x00,
}
