Stage = "development"

[Log]
Level = "debug"

[Database]
Host = "172.31.0.100"
Port = 3306
Schema = "fxmsdb"
User = "fxms"
Password = "fxms123456"

[Redis]
Host = "172.31.0.101"
Port = 6379
Password = "redis123456"

[Sa]
Code = "sa"
Name = "Super Administrator"
Email = "fidel.xu@gmail.com"
Password = "sa"