// Code generated by protoc-gen-go. DO NOT EDIT.
// source: token.proto

package token

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TokenData struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RedirectUri          string   `protobuf:"bytes,3,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"`
	Scope                string   `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	Code                 string   `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`
	CodeCreateAt         int64    `protobuf:"varint,6,opt,name=code_create_at,json=codeCreateAt,proto3" json:"code_create_at,omitempty"`
	CodeExpiresIn        int64    `protobuf:"varint,7,opt,name=code_expires_in,json=codeExpiresIn,proto3" json:"code_expires_in,omitempty"`
	Access               string   `protobuf:"bytes,8,opt,name=access,proto3" json:"access,omitempty"`
	AccessCreateAt       int64    `protobuf:"varint,9,opt,name=access_create_at,json=accessCreateAt,proto3" json:"access_create_at,omitempty"`
	AccessExpiresIn      int64    `protobuf:"varint,10,opt,name=access_expires_in,json=accessExpiresIn,proto3" json:"access_expires_in,omitempty"`
	Refresh              string   `protobuf:"bytes,11,opt,name=refresh,proto3" json:"refresh,omitempty"`
	RefreshCreateAt      int64    `protobuf:"varint,12,opt,name=refresh_create_at,json=refreshCreateAt,proto3" json:"refresh_create_at,omitempty"`
	RefreshExpiresIn     int64    `protobuf:"varint,13,opt,name=refresh_expires_in,json=refreshExpiresIn,proto3" json:"refresh_expires_in,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenData) Reset()         { *m = TokenData{} }
func (m *TokenData) String() string { return proto.CompactTextString(m) }
func (*TokenData) ProtoMessage()    {}
func (*TokenData) Descriptor() ([]byte, []int) {
	return fileDescriptor_3aff0bcd502840ab, []int{0}
}

func (m *TokenData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenData.Unmarshal(m, b)
}
func (m *TokenData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenData.Marshal(b, m, deterministic)
}
func (m *TokenData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenData.Merge(m, src)
}
func (m *TokenData) XXX_Size() int {
	return xxx_messageInfo_TokenData.Size(m)
}
func (m *TokenData) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenData.DiscardUnknown(m)
}

var xxx_messageInfo_TokenData proto.InternalMessageInfo

func (m *TokenData) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *TokenData) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *TokenData) GetRedirectUri() string {
	if m != nil {
		return m.RedirectUri
	}
	return ""
}

func (m *TokenData) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

func (m *TokenData) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *TokenData) GetCodeCreateAt() int64 {
	if m != nil {
		return m.CodeCreateAt
	}
	return 0
}

func (m *TokenData) GetCodeExpiresIn() int64 {
	if m != nil {
		return m.CodeExpiresIn
	}
	return 0
}

func (m *TokenData) GetAccess() string {
	if m != nil {
		return m.Access
	}
	return ""
}

func (m *TokenData) GetAccessCreateAt() int64 {
	if m != nil {
		return m.AccessCreateAt
	}
	return 0
}

func (m *TokenData) GetAccessExpiresIn() int64 {
	if m != nil {
		return m.AccessExpiresIn
	}
	return 0
}

func (m *TokenData) GetRefresh() string {
	if m != nil {
		return m.Refresh
	}
	return ""
}

func (m *TokenData) GetRefreshCreateAt() int64 {
	if m != nil {
		return m.RefreshCreateAt
	}
	return 0
}

func (m *TokenData) GetRefreshExpiresIn() int64 {
	if m != nil {
		return m.RefreshExpiresIn
	}
	return 0
}

type StringValue struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringValue) Reset()         { *m = StringValue{} }
func (m *StringValue) String() string { return proto.CompactTextString(m) }
func (*StringValue) ProtoMessage()    {}
func (*StringValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_3aff0bcd502840ab, []int{1}
}

func (m *StringValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringValue.Unmarshal(m, b)
}
func (m *StringValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringValue.Marshal(b, m, deterministic)
}
func (m *StringValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringValue.Merge(m, src)
}
func (m *StringValue) XXX_Size() int {
	return xxx_messageInfo_StringValue.Size(m)
}
func (m *StringValue) XXX_DiscardUnknown() {
	xxx_messageInfo_StringValue.DiscardUnknown(m)
}

var xxx_messageInfo_StringValue proto.InternalMessageInfo

func (m *StringValue) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type TokenRequest struct {
	Id                   string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Token                *TokenData `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *TokenRequest) Reset()         { *m = TokenRequest{} }
func (m *TokenRequest) String() string { return proto.CompactTextString(m) }
func (*TokenRequest) ProtoMessage()    {}
func (*TokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3aff0bcd502840ab, []int{2}
}

func (m *TokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenRequest.Unmarshal(m, b)
}
func (m *TokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenRequest.Marshal(b, m, deterministic)
}
func (m *TokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenRequest.Merge(m, src)
}
func (m *TokenRequest) XXX_Size() int {
	return xxx_messageInfo_TokenRequest.Size(m)
}
func (m *TokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TokenRequest proto.InternalMessageInfo

func (m *TokenRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TokenRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TokenRequest) GetToken() *TokenData {
	if m != nil {
		return m.Token
	}
	return nil
}

type ErrorResponse struct {
	ErrMessage           string   `protobuf:"bytes,1,opt,name=err_message,json=errMessage,proto3" json:"err_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorResponse) Reset()         { *m = ErrorResponse{} }
func (m *ErrorResponse) String() string { return proto.CompactTextString(m) }
func (*ErrorResponse) ProtoMessage()    {}
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3aff0bcd502840ab, []int{3}
}

func (m *ErrorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorResponse.Unmarshal(m, b)
}
func (m *ErrorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorResponse.Marshal(b, m, deterministic)
}
func (m *ErrorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorResponse.Merge(m, src)
}
func (m *ErrorResponse) XXX_Size() int {
	return xxx_messageInfo_ErrorResponse.Size(m)
}
func (m *ErrorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorResponse proto.InternalMessageInfo

func (m *ErrorResponse) GetErrMessage() string {
	if m != nil {
		return m.ErrMessage
	}
	return ""
}

type TokenResponse struct {
	ErrMessage           string     `protobuf:"bytes,1,opt,name=err_message,json=errMessage,proto3" json:"err_message,omitempty"`
	Token                *TokenData `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *TokenResponse) Reset()         { *m = TokenResponse{} }
func (m *TokenResponse) String() string { return proto.CompactTextString(m) }
func (*TokenResponse) ProtoMessage()    {}
func (*TokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3aff0bcd502840ab, []int{4}
}

func (m *TokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenResponse.Unmarshal(m, b)
}
func (m *TokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenResponse.Marshal(b, m, deterministic)
}
func (m *TokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenResponse.Merge(m, src)
}
func (m *TokenResponse) XXX_Size() int {
	return xxx_messageInfo_TokenResponse.Size(m)
}
func (m *TokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TokenResponse proto.InternalMessageInfo

func (m *TokenResponse) GetErrMessage() string {
	if m != nil {
		return m.ErrMessage
	}
	return ""
}

func (m *TokenResponse) GetToken() *TokenData {
	if m != nil {
		return m.Token
	}
	return nil
}

func init() {
	proto.RegisterType((*TokenData)(nil), "com.fxms.srv.auth.TokenData")
	proto.RegisterType((*StringValue)(nil), "com.fxms.srv.auth.StringValue")
	proto.RegisterType((*TokenRequest)(nil), "com.fxms.srv.auth.TokenRequest")
	proto.RegisterType((*ErrorResponse)(nil), "com.fxms.srv.auth.ErrorResponse")
	proto.RegisterType((*TokenResponse)(nil), "com.fxms.srv.auth.TokenResponse")
}

func init() { proto.RegisterFile("token.proto", fileDescriptor_3aff0bcd502840ab) }

var fileDescriptor_3aff0bcd502840ab = []byte{
	// 539 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xdb, 0x6e, 0xd3, 0x40,
	0x10, 0x6d, 0xee, 0xcd, 0xd8, 0x49, 0xda, 0x15, 0x02, 0xab, 0x45, 0x34, 0x18, 0x84, 0x22, 0x84,
	0x5c, 0x14, 0xbe, 0xa0, 0x2d, 0x15, 0xca, 0x43, 0x85, 0x30, 0x2d, 0x0f, 0xbc, 0x58, 0xae, 0x3d,
	0x49, 0x2d, 0x62, 0x6f, 0xd8, 0x5d, 0x47, 0xed, 0xcf, 0xf1, 0x0b, 0xfc, 0x12, 0xda, 0x59, 0x3b,
	0x75, 0x4b, 0x2b, 0x45, 0x4a, 0x9f, 0x3c, 0x73, 0xe6, 0xec, 0x39, 0xb3, 0x3b, 0x23, 0x83, 0xa5,
	0xf8, 0x2f, 0xcc, 0xbc, 0x85, 0xe0, 0x8a, 0xb3, 0xdd, 0x88, 0xa7, 0xde, 0xf4, 0x3a, 0x95, 0x9e,
	0x14, 0x4b, 0x2f, 0xcc, 0xd5, 0xd5, 0xde, 0xfe, 0x8c, 0xf3, 0xd9, 0x1c, 0x0f, 0x89, 0x70, 0x99,
	0x4f, 0x0f, 0x31, 0x5d, 0xa8, 0x1b, 0xc3, 0x77, 0xff, 0x34, 0xa0, 0x7b, 0xae, 0xcf, 0x7f, 0x0e,
	0x55, 0xc8, 0xf6, 0xa1, 0x1b, 0xcd, 0x13, 0xcc, 0x54, 0x90, 0xc4, 0x4e, 0x6d, 0x58, 0x1b, 0x75,
	0xfd, 0x6d, 0x03, 0x4c, 0x62, 0xf6, 0x02, 0x3a, 0xb9, 0x44, 0xa1, 0x4b, 0x75, 0x2a, 0xb5, 0x75,
	0x3a, 0x89, 0xd9, 0x6b, 0xb0, 0x05, 0xc6, 0x89, 0xc0, 0x48, 0x05, 0xb9, 0x48, 0x9c, 0x06, 0x55,
	0xad, 0x12, 0xbb, 0x10, 0x09, 0x7b, 0x06, 0x2d, 0x19, 0xf1, 0x05, 0x3a, 0x4d, 0xaa, 0x99, 0x84,
	0x31, 0x68, 0x46, 0x3c, 0x46, 0xa7, 0x45, 0x20, 0xc5, 0xec, 0x2d, 0xf4, 0xf5, 0x37, 0x88, 0x04,
	0x86, 0x0a, 0x83, 0x50, 0x39, 0xed, 0x61, 0x6d, 0xd4, 0xf0, 0x6d, 0x8d, 0x9e, 0x10, 0x78, 0xa4,
	0xd8, 0x3b, 0x18, 0x10, 0x0b, 0xaf, 0x17, 0x89, 0x40, 0x19, 0x24, 0x99, 0xd3, 0x21, 0x5a, 0x4f,
	0xc3, 0xa7, 0x06, 0x9d, 0x64, 0xec, 0x39, 0xb4, 0xc3, 0x28, 0x42, 0x29, 0x9d, 0x6d, 0xd3, 0xb2,
	0xc9, 0xd8, 0x08, 0x76, 0x4c, 0x54, 0xf1, 0xe9, 0x92, 0x40, 0xdf, 0xe0, 0x2b, 0xa7, 0xf7, 0xb0,
	0x5b, 0x30, 0x2b, 0x5e, 0x40, 0xd4, 0x81, 0x29, 0xdc, 0xba, 0x39, 0xd0, 0x11, 0x38, 0x15, 0x28,
	0xaf, 0x1c, 0x8b, 0xec, 0xca, 0x54, 0xab, 0x14, 0x61, 0xc5, 0xd0, 0x36, 0x2a, 0x45, 0x61, 0xe5,
	0xf8, 0x01, 0x58, 0xc9, 0xad, 0x58, 0xf6, 0x88, 0xbc, 0x53, 0x54, 0x56, 0x9e, 0xee, 0x1b, 0xb0,
	0xbe, 0x2b, 0x91, 0x64, 0xb3, 0x1f, 0xe1, 0x3c, 0x47, 0xfd, 0xd0, 0x4b, 0x1d, 0x14, 0xd3, 0x33,
	0x89, 0x3b, 0x05, 0x9b, 0x86, 0xec, 0xe3, 0xef, 0x1c, 0xa5, 0x62, 0x7d, 0xa8, 0xaf, 0x06, 0x5c,
	0x4f, 0x62, 0x3d, 0x88, 0x2c, 0x4c, 0xb1, 0x98, 0x2b, 0xc5, 0x6c, 0x0c, 0x2d, 0x5a, 0x2c, 0x1a,
	0xa7, 0x35, 0x7e, 0xe9, 0xfd, 0xb7, 0x59, 0xde, 0x6a, 0x71, 0x7c, 0x43, 0x75, 0x3f, 0x42, 0xef,
	0x54, 0x08, 0x2e, 0x7c, 0x94, 0x0b, 0x9e, 0x49, 0x64, 0x07, 0x60, 0xa1, 0x10, 0x41, 0x8a, 0x52,
	0x86, 0xb3, 0xb2, 0x29, 0x40, 0x21, 0xce, 0x0c, 0xe2, 0xc6, 0xd0, 0x2b, 0x3a, 0x5b, 0xf3, 0xc4,
	0x6d, 0x5f, 0xf5, 0xb5, 0xfb, 0x1a, 0xff, 0x6d, 0x42, 0x8b, 0x40, 0x76, 0x06, 0x6d, 0xf3, 0xd0,
	0xec, 0xe0, 0xb1, 0x83, 0xc5, 0x23, 0xed, 0x0d, 0x1f, 0x20, 0xdc, 0xb9, 0x9d, 0xbb, 0xc5, 0x7c,
	0xb0, 0x7d, 0x4c, 0xf9, 0x12, 0x8f, 0x6f, 0x4e, 0xf4, 0xf6, 0xbe, 0x7a, 0xe0, 0x4c, 0x65, 0x3c,
	0x6b, 0x69, 0x9e, 0x43, 0xbf, 0xd4, 0x3c, 0x32, 0xdb, 0xfa, 0x14, 0xaa, 0x17, 0x30, 0x28, 0x55,
	0xfd, 0x62, 0x29, 0x9f, 0x42, 0xf6, 0x2b, 0x74, 0xbf, 0xa0, 0xda, 0xe0, 0xf6, 0x77, 0xa6, 0xef,
	0x6e, 0xb1, 0x6f, 0x60, 0x91, 0xe0, 0x06, 0x57, 0xbf, 0x2f, 0xe9, 0x83, 0x4d, 0x92, 0x9b, 0xdc,
	0xfb, 0x9e, 0xe6, 0x71, 0xe7, 0xa7, 0x59, 0xad, 0xcb, 0x36, 0xfd, 0x47, 0x3f, 0xfd, 0x0b, 0x00,
	0x00, 0xff, 0xff, 0xab, 0xf2, 0x65, 0x3c, 0x86, 0x05, 0x00, 0x00,
}
