Stage = "development"

[Log]
Level = "debug"

[Database]
Host = "172.31.0.100"
Port = 3306
Schema = "fxmsdb"
User = "fxms"
Password = "fxms123456"

[Auth]
    [[Auth.Clients]]
    ID = "fxras"
    Secret = "fxras123456"
    Domain = "https://127.0.0.1:8080"