LogLevel = "debug"

[Database]
Host = "172.31.0.100"
Port = 3306
Schema = "fxmsdb"
User = "fxms"
Password = "fxms123456"

[Auth]
    [[Auth.Clients]]
    ID = "fxms"
    Secret = "fxmssecret"
    Domain = "https://127.0.0.1:8080"