// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user

import (
	fmt "fmt"
	api "github.com/fidelfly/fxms/mspkg/proto/api"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ValidateRequest struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateRequest) Reset()         { *m = ValidateRequest{} }
func (m *ValidateRequest) String() string { return proto.CompactTextString(m) }
func (*ValidateRequest) ProtoMessage()    {}
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *ValidateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateRequest.Unmarshal(m, b)
}
func (m *ValidateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateRequest.Marshal(b, m, deterministic)
}
func (m *ValidateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateRequest.Merge(m, src)
}
func (m *ValidateRequest) XXX_Size() int {
	return xxx_messageInfo_ValidateRequest.Size(m)
}
func (m *ValidateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateRequest proto.InternalMessageInfo

func (m *ValidateRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *ValidateRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ValidateRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UpdateRequest struct {
	Limit                *api.UpdateInfo `protobuf:"bytes,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Data                 *UserData       `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetLimit() *api.UpdateInfo {
	if m != nil {
		return m.Limit
	}
	return nil
}

func (m *UpdateRequest) GetData() *UserData {
	if m != nil {
		return m.Data
	}
	return nil
}

type UserData struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code                 string               `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name                 string               `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Email                string               `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Password             string               `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	Avatar               int64                `protobuf:"varint,6,opt,name=avatar,proto3" json:"avatar,omitempty"`
	CreateTime           *timestamp.Timestamp `protobuf:"bytes,7,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime           *timestamp.Timestamp `protobuf:"bytes,8,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UserData) Reset()         { *m = UserData{} }
func (m *UserData) String() string { return proto.CompactTextString(m) }
func (*UserData) ProtoMessage()    {}
func (*UserData) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *UserData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserData.Unmarshal(m, b)
}
func (m *UserData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserData.Marshal(b, m, deterministic)
}
func (m *UserData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserData.Merge(m, src)
}
func (m *UserData) XXX_Size() int {
	return xxx_messageInfo_UserData.Size(m)
}
func (m *UserData) XXX_DiscardUnknown() {
	xxx_messageInfo_UserData.DiscardUnknown(m)
}

var xxx_messageInfo_UserData proto.InternalMessageInfo

func (m *UserData) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserData) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *UserData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserData) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserData) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserData) GetAvatar() int64 {
	if m != nil {
		return m.Avatar
	}
	return 0
}

func (m *UserData) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *UserData) GetUpdateTime() *timestamp.Timestamp {
	if m != nil {
		return m.UpdateTime
	}
	return nil
}

type Message struct {
	Say                  string   `protobuf:"bytes,1,opt,name=say,proto3" json:"say,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetSay() string {
	if m != nil {
		return m.Say
	}
	return ""
}

type Request struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Response struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type StreamingRequest struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamingRequest) Reset()         { *m = StreamingRequest{} }
func (m *StreamingRequest) String() string { return proto.CompactTextString(m) }
func (*StreamingRequest) ProtoMessage()    {}
func (*StreamingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *StreamingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamingRequest.Unmarshal(m, b)
}
func (m *StreamingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamingRequest.Marshal(b, m, deterministic)
}
func (m *StreamingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamingRequest.Merge(m, src)
}
func (m *StreamingRequest) XXX_Size() int {
	return xxx_messageInfo_StreamingRequest.Size(m)
}
func (m *StreamingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamingRequest proto.InternalMessageInfo

func (m *StreamingRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type StreamingResponse struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamingResponse) Reset()         { *m = StreamingResponse{} }
func (m *StreamingResponse) String() string { return proto.CompactTextString(m) }
func (*StreamingResponse) ProtoMessage()    {}
func (*StreamingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{7}
}

func (m *StreamingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamingResponse.Unmarshal(m, b)
}
func (m *StreamingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamingResponse.Marshal(b, m, deterministic)
}
func (m *StreamingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamingResponse.Merge(m, src)
}
func (m *StreamingResponse) XXX_Size() int {
	return xxx_messageInfo_StreamingResponse.Size(m)
}
func (m *StreamingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StreamingResponse proto.InternalMessageInfo

func (m *StreamingResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type Ping struct {
	Stroke               int64    `protobuf:"varint,1,opt,name=stroke,proto3" json:"stroke,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{8}
}

func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (m *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(m, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

func (m *Ping) GetStroke() int64 {
	if m != nil {
		return m.Stroke
	}
	return 0
}

type Pong struct {
	Stroke               int64    `protobuf:"varint,1,opt,name=stroke,proto3" json:"stroke,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{9}
}

func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (m *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(m, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

func (m *Pong) GetStroke() int64 {
	if m != nil {
		return m.Stroke
	}
	return 0
}

func init() {
	proto.RegisterType((*ValidateRequest)(nil), "com.fxms.srv.user.ValidateRequest")
	proto.RegisterType((*UpdateRequest)(nil), "com.fxms.srv.user.UpdateRequest")
	proto.RegisterType((*UserData)(nil), "com.fxms.srv.user.UserData")
	proto.RegisterType((*Message)(nil), "com.fxms.srv.user.Message")
	proto.RegisterType((*Request)(nil), "com.fxms.srv.user.Request")
	proto.RegisterType((*Response)(nil), "com.fxms.srv.user.Response")
	proto.RegisterType((*StreamingRequest)(nil), "com.fxms.srv.user.StreamingRequest")
	proto.RegisterType((*StreamingResponse)(nil), "com.fxms.srv.user.StreamingResponse")
	proto.RegisterType((*Ping)(nil), "com.fxms.srv.user.Ping")
	proto.RegisterType((*Pong)(nil), "com.fxms.srv.user.Pong")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 590 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0x5f, 0x6f, 0xd3, 0x3e,
	0x14, 0x5d, 0xba, 0x34, 0xcd, 0xef, 0x56, 0x3f, 0xd8, 0xac, 0x01, 0x25, 0xe5, 0xcf, 0x64, 0x90,
	0xe8, 0x84, 0x94, 0x4c, 0xe5, 0x05, 0x09, 0x84, 0xc4, 0xba, 0x97, 0x3d, 0x4c, 0x42, 0x81, 0x31,
	0x89, 0x17, 0xe4, 0x36, 0x6e, 0xb0, 0x16, 0xc7, 0x21, 0x76, 0x0a, 0xfb, 0x02, 0x7c, 0x20, 0x3e,
	0x21, 0xb2, 0x9d, 0x6c, 0x61, 0xa4, 0xdd, 0x43, 0x24, 0x5f, 0x9f, 0x73, 0xee, 0xbd, 0xc7, 0x37,
	0x36, 0x40, 0x25, 0x69, 0x19, 0x16, 0xa5, 0x50, 0x02, 0xed, 0x2e, 0x04, 0x0f, 0x97, 0x3f, 0xb9,
	0x0c, 0x65, 0xb9, 0x0a, 0x35, 0x10, 0x3c, 0x4d, 0x85, 0x48, 0x33, 0x1a, 0x19, 0xc2, 0xbc, 0x5a,
	0x46, 0x8a, 0x71, 0x2a, 0x15, 0xe1, 0x85, 0xd5, 0x04, 0x0f, 0xb9, 0x2c, 0x2e, 0x52, 0x8b, 0x47,
	0xa4, 0x60, 0xfa, 0xb3, 0x10, 0x3e, 0x87, 0xbb, 0x9f, 0x49, 0xc6, 0x12, 0xa2, 0x68, 0x4c, 0xbf,
	0x57, 0x54, 0x2a, 0x84, 0xc0, 0x5d, 0x88, 0x84, 0x8e, 0x9c, 0x7d, 0x67, 0xf2, 0x5f, 0x6c, 0xd6,
	0x68, 0x0f, 0xfa, 0x94, 0x13, 0x96, 0x8d, 0x7a, 0x66, 0xd3, 0x06, 0x28, 0x00, 0xbf, 0x20, 0x52,
	0xfe, 0x10, 0x65, 0x32, 0xda, 0x36, 0xc0, 0x55, 0x8c, 0x39, 0xfc, 0x7f, 0x56, 0xb4, 0xd3, 0xbe,
	0x84, 0x7e, 0xc6, 0x38, 0x53, 0x26, 0xef, 0x70, 0x7a, 0x2f, 0x34, 0x4d, 0x85, 0xba, 0x15, 0x4b,
	0x3c, 0xc9, 0x97, 0x22, 0xb6, 0x1c, 0x14, 0x81, 0x9b, 0x10, 0x45, 0x4c, 0xb9, 0xe1, 0x74, 0x1c,
	0xfe, 0x63, 0x3a, 0x3c, 0x93, 0xb4, 0x3c, 0x26, 0x8a, 0xc4, 0x86, 0x88, 0x7f, 0xf5, 0xc0, 0x6f,
	0xb6, 0xd0, 0x1d, 0xe8, 0xb1, 0xc4, 0xd4, 0xd9, 0x8e, 0x7b, 0x2c, 0xb9, 0x72, 0xd4, 0x6b, 0x39,
	0x42, 0xe0, 0xe6, 0x84, 0xd3, 0xba, 0x6f, 0xb3, 0xbe, 0x76, 0xe9, 0xae, 0x73, 0xd9, 0xff, 0xdb,
	0x25, 0xba, 0x0f, 0x1e, 0x59, 0x11, 0x45, 0xca, 0x91, 0x67, 0xaa, 0xd5, 0x11, 0x7a, 0x03, 0xc3,
	0x45, 0x49, 0x89, 0xa2, 0x5f, 0xf5, 0x2c, 0x46, 0x03, 0x63, 0x23, 0x08, 0xed, 0xa0, 0xc2, 0x66,
	0x50, 0xe1, 0xa7, 0x66, 0x50, 0x31, 0x58, 0xba, 0xde, 0xd0, 0xe2, 0xca, 0x9c, 0x88, 0x15, 0xfb,
	0xb7, 0x8b, 0x2d, 0x5d, 0x6f, 0xe0, 0x31, 0x0c, 0x4e, 0xa9, 0x94, 0x24, 0xa5, 0x68, 0x07, 0xb6,
	0x25, 0xb9, 0xac, 0xe7, 0xa8, 0x97, 0xf8, 0x31, 0x0c, 0x5a, 0x53, 0x36, 0xfe, 0x9d, 0x6b, 0xff,
	0xf8, 0x11, 0xf8, 0x31, 0x95, 0x85, 0xc8, 0xa5, 0x11, 0x73, 0x99, 0x36, 0x62, 0x2e, 0x53, 0x3c,
	0x81, 0x9d, 0x8f, 0xaa, 0xa4, 0x84, 0xb3, 0x3c, 0x6d, 0xb2, 0xec, 0x41, 0x7f, 0x21, 0xaa, 0x5c,
	0xd5, 0x87, 0x6d, 0x03, 0x7c, 0x00, 0xbb, 0x2d, 0x66, 0x9d, 0xb0, 0x9b, 0xfa, 0x04, 0xdc, 0x0f,
	0x2c, 0x4f, 0xf5, 0x41, 0x4a, 0x55, 0x8a, 0x0b, 0x5a, 0xc3, 0x75, 0x64, 0x70, 0xb1, 0x1e, 0x9f,
	0xfe, 0x76, 0xc1, 0xd5, 0x73, 0x47, 0xef, 0xc1, 0x9d, 0x91, 0x2c, 0x43, 0x41, 0xc7, 0xbf, 0x52,
	0x77, 0x1b, 0x8c, 0x3b, 0x31, 0xdb, 0x1f, 0xde, 0x42, 0xe7, 0xe0, 0xd9, 0xb6, 0xd1, 0xb3, 0x0e,
	0xe2, 0x4d, 0xef, 0xc1, 0xf3, 0xcd, 0xa4, 0x26, 0xed, 0xa1, 0x83, 0x8e, 0xc0, 0xd7, 0x26, 0x8d,
	0x91, 0x07, 0x1d, 0x2a, 0x0d, 0x06, 0x9d, 0x80, 0xc8, 0x53, 0xbc, 0x35, 0x71, 0x0e, 0x1d, 0xf4,
	0x0e, 0xbc, 0x99, 0xf9, 0x45, 0xd0, 0xa6, 0xdb, 0x10, 0xb4, 0xaf, 0xd5, 0x49, 0xd2, 0x32, 0x37,
	0x03, 0xcf, 0x5e, 0x33, 0xb4, 0xdf, 0xa5, 0x6f, 0x5f, 0xd5, 0xf5, 0x49, 0xde, 0x82, 0x1b, 0x53,
	0x92, 0xa0, 0x6e, 0x42, 0xb0, 0xa9, 0x33, 0xbc, 0x85, 0x5e, 0x83, 0x77, 0x4c, 0x33, 0xaa, 0xe8,
	0x3a, 0xfd, 0xda, 0xba, 0xa7, 0xe0, 0x37, 0xaf, 0x14, 0xc2, 0x1d, 0x45, 0x6e, 0x3c, 0x61, 0xb7,
	0x34, 0x72, 0x74, 0xf0, 0xe5, 0x45, 0xca, 0xd4, 0xb7, 0x6a, 0xae, 0x69, 0xd1, 0x92, 0x25, 0x34,
	0x5b, 0x66, 0x97, 0x91, 0xe6, 0x47, 0xb2, 0x5c, 0xd5, 0x0f, 0xa5, 0x56, 0xcd, 0x3d, 0xb3, 0x7e,
	0xf5, 0x27, 0x00, 0x00, 0xff, 0xff, 0x14, 0xc1, 0x82, 0xba, 0x83, 0x05, 0x00, 0x00,
}
